package netbanking00;
import java.io.Serializable;
import java.util.Date;
/**
 * 支店マスタ モデルクラス.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
public class DAO_TMBankBranch implements Serializable {

    /** serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** BRANCH_ID. */
    private Integer branchId;

    /** BRANCH_NAME. */
    private String branchName;

    /** CREATE_DATE. */
    private Date createDate;

    /** CREATE_USER. */
    private String createUser;


    /**
     * コンストラクタ.
     */
    public DAO_TMBankBranch() {
    }

    /**
     * BRANCH_ID を設定します.
     *
     * @param branchId
     *            BRANCH_ID
     */
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }

    /**
     * BRANCH_ID を取得します.
     *
     * @return BRANCH_ID
     */
    public Integer getBranchId() {
        return this.branchId;
    }

    /**
     * BRANCH_NAME を設定します.
     *
     * @param branchName
     *            BRANCH_NAME
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    /**
     * BRANCH_NAME を取得します.
     *
     * @return BRANCH_NAME
     */
    public String getBranchName() {
        return this.branchName;
    }

    /**
     * CREATE_DATE を設定します.
     *
     * @param createDate
     *            CREATE_DATE
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * CREATE_DATE を取得します.
     *
     * @return CREATE_DATE
     */
    public Date getCreateDate() {
        return this.createDate;
    }

    /**
     * CREATE_USER を設定します.
     *
     * @param createUser
     *            CREATE_USER
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * CREATE_USER を取得します.
     *
     * @return CREATE_USER
     */
    public String getCreateUser() {
        return this.createUser;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((branchId == null) ? 0 : branchId.hashCode());
        return result;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        } if (obj == null) {
            return false;
        } if (getClass() != obj.getClass()) {
            return false;
        }
        DAO_TMBankBranch other = (DAO_TMBankBranch) obj;
        if (branchId == null) {
            if (other.branchId != null) {
                return false;
            }
        } else if (!branchId.equals(other.branchId)) {
            return false;
        }
        return true;
    }
}


